

GET http://localhost:3200/tasks
Content-Type: application/json


POST http://localhost:3200/tasks
Content-Type: application/json

{
    "title": "Title555555",
    "date": "2023-02-10-T12:00:00Z",
    "description": "Some description",
    "priority": "normal",
    "status": "todo"
}


PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "0013aee9-d724-43a5-801b-b06ab027ad7c",
    "status": "inProgress"
}